spring:
  application:
    name: cc-process-centre-next-backend
---
spring:
  config:
    activate:
      on-profile: "!cc-prod && !cc-local"
    import: configserver:https://intragate.test.ec.europa.eu/spring-cloud-config-np
  cloud:
    config:
      label: env/DEV
      fail-fast: true
---
spring:
  config:
    activate:
      on-profile: "cc-local"
  cloud:
    config:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: "cc-docker"
  cloud:
    config:
      enabled: false