# Default values for chart cc-echecklist-backend
replicaCount: 1

env: {}
debug:
  port: 5005

image:
  registry: csdr-docker.devops.tech.ec.europa.eu
  repository: cc-process-centre-next-backend
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  metrics: "/metrics"

prometheus:
  release: "prometheus"

ingress:
  enabled: true
  annotations: {}
  domain: tena.k8s.beta.cop.cec.eu.int
  
# Load system-config files either from server uri or from local file system
systemconfig:
  uri: https://intragate.test.ec.europa.eu/spring-cloud-config-np
  vault: true
  label: env/DEV
  name: cc-process-centre-next-backend
  local: false

kafka:
  tls: true

probes:
  enabled: true
  readinessProbe:
    httpGet:
      path: /actuator/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
  livenessProbe:
    httpGet:
      path: /actuator/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
  startupProbe:
    httpGet:
      path: /actuator/health
    failureTreshold: 30
    periodSeconds: 60

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
