{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ing
spec:
  rules:
  - host: {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.domain }}
{{- end }}
