{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Values.prometheus.release }}
spec:
  endpoints:
  - path: {{ .Values.service.metrics }}
    port: http
  namespaceSelector:
    matchNames:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{ end -}}
